# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnTrack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OnTrack
  pod "Parse"
  pod "AlamofireImage"
  pod 'MaterialComponents/Chips'

  target 'OnTrackTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OnTrackUITests' do
    # Pods for testing
  end

end
